---
- hosts: all
  become: true
  tasks:
    - name: Create backup postgresql database
      shell: " pg_dump  -h 10.4.4.10 -p 5432 -U awx -F c -b -v -f /home/backup/DBTower/towerDB2.backup "
      ignore_errors: yes



