---
- hosts: postgresql1
  become: true
  tasks:
    - name: Create backup postgresql database
      shell: " pg_dump agencia -h 10.4.4.10 -p 5432 -U postgres -F c -b -v -f /home/backup/DBTower/towerDB2.backup "
      ignore_errors: no
      register: command_output
    - debug: msg="{{command_output.stdout}}"



