---
- hosts: salud
  become: true
  tasks:
    - name: Create backup database "his" 
      shell: " docker exec postgres9.4 pg_dump his -F c -b -U postgres > /home/centos/mnoguera/Docker/Postgres9.4/restore/restore-DBhis{{ date }}.backup "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no
      register: command_output
    - debug: msg="{{command_output.stdout}}"

- hosts: salud
  become: true
  tasks:
    - name: Copy backup in volumen docker
      shell: " docker cp /home/centos/mnoguera/Docker/Postgres9.4/restore/restore-DBhis{{ date }}.backup postgreslab_1:/var/lib/postgresql/data/ "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no

- hosts: salud
  become: true
  tasks:
    - name: Create database "his" in postgreslab1
      shell: " docker exec postgreslab_1 createdb -U postgres his "
      ignore_errors: no

- hosts: salud
  become: true
  tasks:
    - name: Create restore database "his" in postgreslab1
      shell: " docker exec postgreslab_1 pg_restore -U postgres -d his /var/lib/postgresql/data/restore-DBhis{{ date }}.backup "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no
