---
- hosts: his_hbo_produccion
  become: true
  become_user: ansible
  tasks:
    - name: Copy file backup to server his_hbo_homologada
      shell: " scp /home/ansible/mnoguera/backups/database-his{{ date }}.backup ansible@his_hbo_homologada:/home/ansible/mnoguera/restore "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no
  

