---
- hosts: his_hbo_produccion
  become: true
  tasks:
    - name: Create backup database his
      shell: " docker exec name_container pg_dump his -F c -b -U postgres > /home/ansible/mnoguera/backups/database-his{{ date }}.backup "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no
      register: command_output
    - debug: msg="{{command_output.stdout}}"

