---
- hosts: his_hbo_homologada
  become: true
  tasks:
    - name: Create database his in his_hbo_homologada
      shell: " psql -U datasystem CREATE DATABASE his{{ date }}; "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no

- hosts: his_hbo_homologada
  become: true
  tasks:
    - name: Create restore database his
      shell: " pg_restore -h his_hbo_homologada -p 5432 -U datasystem -d his{{ date }} -v /home/ansible/mnoguera/backups/database-his{{ date }}.backup "
      vars:
          date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      ignore_errors: no

